version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:80"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
